// Generated by `mcp__supabase__generate_typescript_types`.
// Regenerate after every migration to keep this file in sync with the DB.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      deals: {
        Row: {
          catering: string;
          country: string;
          created_at: string | null;
          created_via: string;
          description: string;
          destination: string;
          duration: number;
          flight_time: string;
          highlights: string[];
          id: string;
          image_url: string | null;
          inclusions: string[];
          keywords: string[];
          price_per_person: number;
          provider: string;
          provider_url: string;
          rating: number;
          ratings: Json;
          region: string;
          source: string;
          start_date: string;
          submitted_by: string | null;
          title: string;
          type: string;
          updated_at: string | null;
        };
        Insert: {
          catering: string;
          country: string;
          created_at?: string | null;
          created_via?: string;
          description: string;
          destination: string;
          duration: number;
          flight_time: string;
          highlights?: string[];
          id: string;
          image_url?: string | null;
          inclusions?: string[];
          keywords?: string[];
          price_per_person: number;
          provider: string;
          provider_url: string;
          rating: number;
          ratings: Json;
          region: string;
          source?: string;
          start_date: string;
          submitted_by?: string | null;
          title: string;
          type: string;
          updated_at?: string | null;
        };
        Update: {
          catering?: string;
          country?: string;
          created_at?: string | null;
          created_via?: string;
          description?: string;
          destination?: string;
          duration?: number;
          flight_time?: string;
          highlights?: string[];
          id?: string;
          image_url?: string | null;
          inclusions?: string[];
          keywords?: string[];
          price_per_person?: number;
          provider?: string;
          provider_url?: string;
          rating?: number;
          ratings?: Json;
          region?: string;
          source?: string;
          start_date?: string;
          submitted_by?: string | null;
          title?: string;
          type?: string;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      vacation_activities: {
        Row: {
          created_at: string | null;
          currency: string | null;
          id: string;
          is_reserved: boolean | null;
          location: string | null;
          name: string;
          notes: string | null;
          price_per_person: number | null;
          sort_order: number | null;
          updated_at: string | null;
          url: string | null;
          vacation_plan_id: string;
        };
        Insert: {
          created_at?: string | null;
          currency?: string | null;
          id?: string;
          is_reserved?: boolean | null;
          location?: string | null;
          name: string;
          notes?: string | null;
          price_per_person?: number | null;
          sort_order?: number | null;
          updated_at?: string | null;
          url?: string | null;
          vacation_plan_id: string;
        };
        Update: {
          created_at?: string | null;
          currency?: string | null;
          id?: string;
          is_reserved?: boolean | null;
          location?: string | null;
          name?: string;
          notes?: string | null;
          price_per_person?: number | null;
          sort_order?: number | null;
          updated_at?: string | null;
          url?: string | null;
          vacation_plan_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "vacation_activities_vacation_plan_id_fkey";
            columns: ["vacation_plan_id"];
            isOneToOne: false;
            referencedRelation: "vacation_plans";
            referencedColumns: ["id"];
          },
        ];
      };
      vacation_plans: {
        Row: {
          created_at: string | null;
          deal_id: string | null;
          id: string;
          name: string;
          notes: string | null;
          updated_at: string | null;
          user_id: string;
        };
        Insert: {
          created_at?: string | null;
          deal_id?: string | null;
          id?: string;
          name: string;
          notes?: string | null;
          updated_at?: string | null;
          user_id?: string;
        };
        Update: {
          created_at?: string | null;
          deal_id?: string | null;
          id?: string;
          name?: string;
          notes?: string | null;
          updated_at?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "vacation_plans_deal_id_fkey";
            columns: ["deal_id"];
            isOneToOne: false;
            referencedRelation: "deals";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
